### ISSUE TITLE
Import production DB to https://theincline.spiritedphase1.wpengine.com

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1040]
## Task list
- [x] Pick a day - currently set for Tuesday
- [x] Install WP DB Migrate Pro on `theincline.spiritedphase1`
- [x] Tell everyone in PIT to stop publishing the news after a certain time
- [x] Dump the DB
- [x] Load the DB. After we have a fresh database, CM will truncate the tables for Billy Penn and Denverite, and then will send the file over
- [x] ETL the DB and get it loaded locally
- [x] Confirm that works, and then ETL the local DB to wherebyus
- [x] Cut over the DNS

**Comment by ErnieAtLYD** [comment]
Getting ready to do this tomorrow (Tuesday 4/2) at 2:30pm ET.
