### ISSUE TITLE
SCOPING: Member Campaigns for issues series

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1057]
DOD: A scope of work for this task 

- [x] Meeting Wednesday, 4/3, at 12 - 12:30 est. @michaelschofield and @alexandraleighs 
- [x] Create a scope of work for the desired featureset. @michaelschofield 
- [ ] Review scope on Friday with @michaelschofield @alexandraleighs rsm

# Campaigns 1.0

## Featureset summary
* At any given point, we can create a "new campaign" where we can set one or more milestones.
* We can optionally set a start and an end date, or just let the campaign be active forever.
* A user can become a member from that campaign landing page.
  * Becoming a member via campaign increments the campaign progress by 1. 
  * Becoming a member via campaign logs that activity, so that we can identify the users who joined by campaign
* Once the campaign progress reaches a milestone, that milestone is unlocked.
* We can see a list of users in the campaign's backend who participated.
* Membership through this campaign adds a discount coupon to checkout. 

### 1.0 Stretch
* We can associate a milestone with an IssueSeries ID, so that IssueSeries content can reflect that it was supported by a specific campaign

## Flow requirements
* Membership selection, checkout, and joining all happen on the same page. 

## Featureset scope
* At any given point, we can create a "new campaign" where we can set one or more milestones.
* We can optionally set a start and an end date, or just let the campaign be active forever.
1. We need to make the existing campaign post type available outside of referrals. (2)
2. We need to create CampaignService with the updated schemea (without breaking referral campaign behavior) (5)
3. We need to create a new or update the existing Campaign editor with all the new fields. (3)
4. We need to create a milestone object / table (3)

* A user can become a member from that campaign landing page.
5. We need to design and create a `/campaign/{slug}` landing page. 
5a. Landing page nano-sprint using as many of the existing components we have from the design system (3)
5b. Code this (5)
5c. Figure out how to apply our one-page checkout magic (5)
    - Becoming a member via campaign increments the campaign progress by 1. 
6. We need to augment the new member process to account for campaign association (3)
    -- Becoming a member via campaign logs that activity, so that we can identify the users who joined by campaign
7. We need to create a CampaignUserRelationship table / association somewhere to log this (3)

* Once the campaign progress reaches a milestone, that milestone is unlocked.
* We can see a list of users in the campaign's backend who participated.
8. We need to create an API and backend user action to retrieve and display this list. (3)

* Membership through this campaign adds a discount coupon to checkout. 
9. If a coupon is associated with a campaign, we need to apply that to checkout (2)

## Campaign model
Name | Type | Desc
----- | ----- | ------
awardTiers |  | If you refer or donate a certain amount, these things get unlocked
campaignType | tinyint | an integer that maps to a campaign type, e.g., membership, referral, fundraiser
dateEnd | |
dateStart | |
id | |
milestones | | 
slug | |
title

### CampaignUserRelationship
- campaignId
- id
- userId 

### Milestone
- amount
- description
- id
- title
