### ISSUE TITLE
Transactional email tasks

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1097]
Prepare tasks for transactional emails to come from whereby.us rather than city 

## Stories
*JOB STORY 1*
WHEN we are sending out WooCommerce or Event Followup Emails
AND the emails have to be able to sent from @whereby.us
WE WANT to have in the footer than the subsite "is a WhereBy.Us company"
SO we can increase WBU's brand recognition
AND users are not confused when they receive an email from WhereBy.Us 

*JOB STORY 2*
WHEN we are sending out WooCommerce or Event Followup Emails
AND the emails have to be able to sent from @whereby.us
WE WANT to have the emails sent from a transactional address, such as `store` or `events`
AND we the reply-to to go to `hello@[city specific website]` if possible
SO THAT if someone replies to a transactional email, Kristem won't have to worry about where the email needs to be routed

*JOB STORY 3*
~~WHEN we are sending out WooCommerce or Event Followup Emails
AND the emails have to be able to sent from @whereby.us
WE WANT to include brand name in all transaction email subject lines
SO THAT if their email client says "WhereBy.Us," they have a clearer understanding of what the transactional email is referring to~~

## Tasks

 - [ ] Explicitly state in transactional email footers the sub-site is a WhereBy.Us company
 - [x] Create a transactional specific email instead of hello@ -> should be orders@ or shop@ or something similar
 - [x] Include brand name in all transaction email subject lines

**Comment by carogea** [comment]
This can be done by multiple people

**Comment by michaelschofield** [comment]
```
WHEN we are sending out WooCommerce or Event Followup Emails
AND the emails have to be able to sent from @whereby.us
WE WANT to have the emails sent from a transactional address, such as store or events
AND we the reply-to to go to hello@[city specific website] if possible
SO THAT if someone replies to a transactional email, Kristem won't have to worry about where the email needs to be routed
```

Unfortunately I don't think this is possible on a multisite.

**Comment by michaelschofield** [comment]
We're ready to flip the switch on Amazon SES for transactional stuff whenever. Emails will come from orders@whereby.us.
