### ISSUE TITLE
Automate newsletter template compilation with Emogrifier

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1222]
@michaelschofield commented on [Tue Apr 16 2019](https://github.com/wherebyus/newsletterservice/issues/6)

**Note**: this could be either in wbu-newsletters or in newsletterService, the latter would require a refactor of the send test emails functionality, but there's benefit to that and the real question comes down to how much time we may want to spend.

**Warning**: This is totally *feasible*, but our current environment may make it difficult and prone to timeouts. I'd recommend pursuing this only if you're okay with, in the end, burning the hours spent on this ticket without a deliverable.

**Low pri**: There are a lot more wbu-newsletter process improvements we can make that would have a lot more impact than automating this build (which right now is a _task_ that involves some copying and pasting, but isn't that huge of a timesuck - it'd save minutes not hours).

## Tasks
- [ ] Add Pelago/Emogrifier via composer
- [ ] Remove the `<style>` tags and corresponding CSS from `raw-newsletter-template` and move them into a new CSS file. Load the parent design-system based CSS from the design system itself, so that it never has to be manually updated
- [ ] When a test email is generated, emogrify the `raw-newsletter-template` html and load the CSS file[s]. Note that the inlineStyle methods we do when we send test emails should be run on the _emogrified_ template.
- [ ] The resulting emogrified newsletter template must function identically to the current production newsletter. That means: responsive font sizing and the whole shebang. Test rigorously in litmus.
