### ISSUE TITLE
Co-author functionality in articles

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#1238]
When I'm an editor or a storyteller I want to add a Your View post with multiple editors in a simpler way so that it's straightforward and I don't have to rip my hair out.

### Definition of done
1. On the admin side, it's straightforward to add co-authors
2. There is documentation on how to do the above.
3. On the user side, it's evident that two people have authored the article

### Tasks
- [ ] Install the co-authors plugin into `composer.json`, then activate (1)
- [ ] [Implement template](https://wpvip.com/documentation/incorporate-co-authors-plus-template-tags-into-your-theme/) to show additional co-author (2)
- [ ] Update WordPress manual in library.whereby.us to provide information on how to do this (1)
- [ ] Brag about this at the show and tell on Fridays 😛 (1)

**Comment by ErnieAtLYD** [comment]
Branch started here: https://github.com/wherebyus/frodo/tree/issue-1238
