### ISSUE TITLE
Refactor: The Call to Action should use the newsletter ID that the rest of the site is configured with, rather than whatever value it's reading now

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1274]
## Feature or problem
Describe the feature or problem here.

### Reproduction
The fact that whatever List ID value that Frodo.vue (and enqueue-scripts.php, which is funneling that value into the Vue component) is _different_ from everything else is making testing more time-consuming than it needs to be. This is a straightforward fix that will, in the future, carve a few minutes of confusion off our lives.

## Done
- [ ] The Call to Action should be configured to use the same list ID that is returned by MailChimpService::getListId
* This can optionally be passed through a PHP variable into Frodo.vue, but there is also an API the call to action can query that returns that ID: https://thenewtropic.com/wp-json/whereby/api/newsletters/lists

### Suggested priority
priority-low

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check
