### ISSUE TITLE
Launch new Incline site

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#1302]
"Flipping the switch" on theincline.com domain (10ishpm?)

## Subtasks
- [x] Point theincline.com domain to the pittsburgh instance
- [x] ensure that it has an SSL cert
- [x] point archive.theincline.com to the spirtied1 instance
- [x] uh it probably won't have an ssl cert ^ and we probably can't add one ^ but if we can let's try
- [x] Add incline redirect snippet to the wpengine nginx conf
- [x] click around and make sure things work.

## Feature or problem
Describe the feature or problem here.

### Definition of done
How will we know when this feature is complete?

## UX Check
- [ ] Is there evidence that this is a demonstrable need in WhereByUX?
- [ ] Do insights from such demonstrable need, if it exists, suggest that the thing we want to deliver is a good idea?

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code (2)
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing (3)
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check
