### ISSUE TITLE
PIT: verify membership-purchased order emails/receipts

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1314]
## Feature or problem
Before The Incline woo membership system is turned on, let's make sure membership-purchased order emails / receipts are turned on too.

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* michael

### Tasks
 - [ ] Clone default emails in `/wp-admin/admin.php?page=followup-emails` from a WBU site to PIT (2)

**Comment by ErnieAtLYD** [comment]
- [x] Member re-engagement: Cancelled
 - [x] Member re-engagement: Expired
 - [x] Order failed
 - [x] Email Renewal- Three Day Prior
 - n/a - Annual Email Renewal - Three Days Prior
