### ISSUE TITLE
MailChimp returns HTML with its error, so the `optin` component needs to accommodate that.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1410]
### Reproduction
Try to subscribe with an email that's already subscribed. The error message will return an `a` that should render, rather than print code.

### Suggested priority
priority-high

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?
- [ ] HTML that's part of the `optin` error response that appears underneath the input should be rendered.

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code (1)
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing (1)

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.
- [ ] Try to subscribe using an email that is already subscribed to a list. The resulting response, which should be something like "so-and-so is already subscribed," which includes a link to their mailchimp profile, should render as an actual link.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check
