### ISSUE TITLE
Setup automatic subscription tagging for three new sources

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1453]
* Story page tag: [site_story]
* NL archive page tag: [site_NL]
* Users who create site login when purchasing membership tag: [site_membership]

## Subtasks
- [ ] Create an inline optin in the design system
- [ ] Use the inline option on the post template, the newsletter archive.
- [ ] Update the login component so new subscriptions are tagged.
