### ISSUE TITLE
On the `home` component, account for cases when an image doesn't exist in the API.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1464]
## Feature or problem
Describe the feature or problem here.

### Reproduction
If we use an image smaller than 768px, it won't appear as a "medium-large" image in the API. The `home` component will still create a `card` for that article, but it won't have a background image.  

### Suggested expected behavior
- [ ] We need a decision how to handle this (e.g., not show the card, render a smaller version of the image, show a default background, etc.)
- [ ] Implement it.

### Suggested priority
priority-medium

### Stakeholders
*Submitted:* michael

### Definition of done
How will we know when this feature is complete?

### Subtasks
A detailed list of changes that need to be made or subtasks. One checkbox per.
- [ ] Brew the coffee

## Developer estimate
To help the team accurately estimate the complexity of this task, 
take a moment to walk through this list and estimate each item. At the end, you can total
the estimates and round to the nearest prime number. 

If any of these are at a `5` or higher, or if the total is above a `5`, consider breaking
this issue into multiple smaller issues.

- [ ] Changes to the database ()
- [ ] Changes to the API ()
- [ ] Testing Changes to the API ()
- [ ] Changes to Application Code ()
- [ ] Adding or updating unit tests ()
- [ ] Local developer testing ()

## Additional estimate
- [ ] Code review ()
- [ ] QA Testing ()
- [ ] Stakeholder Sign-off ()
- [ ] Deploy to Production ()

## QA Notes
Detailed instructions for testing, one checkbox per test to be completed.

### Contextual tests
- [ ] Accessibility check
- [ ] Cross-browser check (Edge, Chrome, Firefox)
- [ ] Responsive check
