### ISSUE TITLE
For partner events, let's introduce the end-date option to account for partner festivals and the like.

### ISSUE THREAD

**Issue by michaelschofield** [wherebyus/general-tasks#1691]
## Subtasks
- [ ] Add the field to the editor and event bot
- [ ] Ensure the language is sufficiently clear that the end-date only applies to partner events
- [ ] The generated aggregate needs to have the right sentence structure to account for multiple days. E.g., (Thursday, October 2nd -- Friday, October etc).
