### ISSUE TITLE
Main section atomization

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#243]
### Job story
- When I am reading an email newsletter, I want to share the main section of an email newsletter so my friends can read and share as well.
- When I am reading an email newsletter section from the website, I want to be able to comment on the article so I can feel a place of belonging.
- When I am reading an email newsletter section from the website, I want to be able to access the rest of the newsletter so I can read the entire newsletter as a whole and understand its context.

### Acceptance criteria
 - [ ] There is a way I can comment and share via twitter at the bottom of the main section of the email newsletter.
 - [ ] If I click the comment icon from the email newsletter, it will lead me to the web link of the newsletter section.
 - [ ] There is a unique web URL for the main section of each newsletter
 - [ ] If I click the FB icon from the email newsletter, I will be directed to the facebook.com's "Share a link" web page.
 - [ ] If I click the twitter icon from the email newsletter, I will be directed to the twitter.com "Share a link with your followers" web page.
 - [ ] If share through either of the methods above, the input box will be prepopulated with the URL of the web link of the newsletter section.
 - [ ] If share through either of the methods above, the input box will be prepopulated with some sort of copy, possibly the section subject. 

### DEFINITION OF READY FOR TRACKING FEATURES OR PROJECTS
If the answer to any of the following is no and you need this, leave a comment and let Ernie know.

- [x] Is there a two or three word summary for a title?
- [ ] Is this "thing" small enough to fit in one sprint (if not, consider breaking down into smaller tasks)?
- [x] Is there a job story? (When I ___, I want to ____ so that _____)
- [ ] Is there an external contact if you have product questions, if applicable?
- [x] Is there [acceptance criteria](https://www.boost.co.nz/blog/2010/09/acceptance-criteria)?
