### ISSUE TITLE
Indentation for bulleted lists is off

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#761]
## Feature or problem
List styles aren't up to snuff. 

Reference link: https://pulp.town/newsletter/2019-02-04-want-to-know-orlandos-best-late-night-eats/

![image.png](https://images.zenhubusercontent.com/5b3b8639fc589b1d091c443c/e1f3ff1c-92ac-47c5-a62f-0cbd4e1be0d4)

## Subtasks
- [ ] Styles -- if not already there -- are added for ordered and unordered lists to the global stylesheet in the design system
- [ ] Bonus: Create a simple `<list>` component that documents these list styles in the design system.
- [ ] Conflicting list styles in Frodo are deleted

## QA
- Lists --ordered and unordered -- should look consistent with their surrounding type, including margin, padding, and line-height. They should look correct in any content type.

**Comment by ErnieAtLYD** [comment]
This is a dupe with #836 so I'm closing
