### ISSUE TITLE
Migrate MailChimp ownership from Spirited Media -> WBU

### ISSUE THREAD

**Issue by ErnieAtLYD** [wherebyus/general-tasks#962]
## Definition of ready
 - The Incline mailing list should be owned by WhereBy.Us. 
 - The Incline editors should be able to log in and edit their newsletters without changes to their workflow
 - The list ID of a newsletters shouldn't change from the previous owner to the current owner. 
 - NICE TO HAVE: the prior campaigns and accompanying data could transfer as well

### References
- There is a folder in the team drive with info on what we'll be doing here, incl. the google doc below. we can also store data exports in this folder
- https://mailchimp.com/help/transfer-ownership-of-an-account/
- [Pittsburgh MailChimp migration notes google doc](https://docs.google.com/document/d/1fFIIA7X7b8JfoSlECg5dfi9Wfl7DTHiqfiCzvSgruJ4/edit?usp=sharing)

### Tasks
 - [x] Give Carolyn access to MailChimp (admin account)
 - [x] Get Carolyn access to Mailchimp for The Incline
-  [x] Carolyn and Brian meet to hash out what needs to be done

**Comment by ErnieAtLYD** [comment]
@carogea It looks like you can't "transfer" a list from one account to another, only export and reimport again. https://mailchimp.com/help/combine-multiple-accounts/

If that's the case we'll lose a lot of information like campaigns and stuff. It looks like we'll be losing templates as well so we'll need to make sure the WBU account imports the versions

**Comment by ErnieAtLYD** [comment]
Tristan has given us The Incline's MailChimp data:
https://wherebyus.slack.com/files/U2G05MGJY/FH5ETAMBQ/members_export_1676c97ae0.zip
