### ISSUE TITLE
Scope The Incline's "stories"

### ISSUE THREAD

**Issue by carogea** [wherebyus/general-tasks#988]
DOD: Determine the following things
- [ ] Overview of how these work, different story lists, other general information
- [ ] What's the user benefit/need?
- [ ] Subscriber numbers for stories vs. The Incline's newsletter. How many readers are we potentially losing if we don't keep stories? <- figure out what to do w story subscribers who don't get the NL
- [ ] How much of editors' and other employees time would it take up?
- [ ] Monetization opportunities
- [ ] Technical implications 

Anything else?
